### ISSUE TITLE
'main' panicked at 'cannot call wasm-bindgen imported functions on non-wasm targets', 

### ISSUE THREAD

**Issue by victorhernandezo** [nlern/yew-app#1]
'main' panicked at 'cannot call wasm-bindgen imported functions on non-wasm targets',

**Comment by shantanu-dutta** [comment]
Hi @victorhernandezo! Thanks for raising this issue!

I am sorry that there is no README file present in this repo with instructions to tell the user how to execute this code. I will add a README soon. Meanwhile, you can refer to [this article][wasm-tutorial-link] which I used to create this app.

For me executing these steps worked:

1. Install rust if you haven’t already
2. Install trunk: `cargo install trunk`
3. Add wasm32 target by executing `rustup target add wasm32-unknown-unknown`
4. Inside code repo execute `trunk serve`.


Hope this helps! Please let me know in case of any further issues.


[wasm-tutorial-link]: https://infinite-improbability.org/rust_wasm_photos/ "Creating an app in webassembly"
